Update info
daiterranova/Portfolio pull request #31
Opened 2024-11-16 22:25 UTC by daiterranova

- Update resume info (experience, about me section, projects) and corresponding assets of new projects added.

Could you please checkout about grammar and description?

I am opening new issues about design in general since the cards don't have a controlled size. Feel free to add to this conversation any points that you consider that need to be attended.

Young regards,

2024-11-17 14:41 UTC, reynico commented
I think it would be good to standardize the cards' sizes in the portfolio section so all cards have the same size.

<img width="769" alt="image" src="https://github.com/user-attachments/assets/d8a2534d-7a78-46b8-8c0d-fbbb722542da">

2024-11-17 14:41 UTC, reynico requested changes

2024-11-17 14:41 UTC, reynico commented on src/utils/resumeData.js
> +    about: 'Fullstack Web Developer nearly two years of  professional experience, proficiency in React, CSS, HTML, JavaScript, JS Libraries, and MUI library. Experienced in backend development with D
```suggestion
    about: 'Fullstack Web Developer with nearly two years of professional experience, proficiency in React, CSS, HTML, JavaScript, JS Libraries, and MUI library. Experienced in backend development with Django, PostgreSQL, ElasticSearch, and Python. I am skilled at crafting user-focused, high-impact solutions independently and as part of cross-functional teams. Currently learning about system design patterns and testing with unittest/pytest suites and GitHub actions. Additionally, my professional experience includes a solid expertise in risk analysis, dedication to customer service and experience managing,  coordinating and mentoring people. Outside of work, I am passionate about learning from others in the community and collaborating toward the common good.',
```

2024-11-17 15:10 UTC, daiterranova commented
> I think it would be good to standardize the cards' sizes in the portfolio section so all cards have the same size.
> 
> <img alt="image" width="769" src="https://private-user-images.githubusercontent.com/715768/386968819-d8a2534d-7a78-46b8-8c0d-fbbb722542da.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE4NTYyOTEsIm5iZiI6MTczMTg1NTk5MSwicGF0aCI6Ii83MTU3NjgvMzg2OTY4ODE5LWQ4YTI1MzRkLTdhNzgtNDZiOC04YzBkLWZiYmI3MjI1NDJkYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExN1QxNTA2MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZTU4N2ViZTI5OWExODIzZjY1YzYzZWMyZDk2Y2I4NjdiYzQzNjMyZTViZDU0MTQ0ZTUyN2RkNmFjYzhlZjJiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.i6DzkYCFLRmxBVK4_SNFhu0S9MtxyvQpFF2W2G_IEAA">

yeah, that it's already on the table with this issue #35

2024-11-19 20:29 UTC, reynico approved these changes

2024-11-19 22:37 UTC, merged